---
title: "Preliminary Visualizations for 1st Presentation"
author: "Gillian"
date: "2/15/2022"
output: html_document
---

```{r setup, include=FALSE}
# R Markdown options
knitr::opts_chunk$set(echo = T, warning = F, error = F, message = F, results = F, cache=T)

# LOAD PACKAGES
library(sf)
library(riem)
library(caret)
library(spdep)
library(knitr)
library(gifski)
library(tigris)
library(mapview)
library(geojsonR)
library(tidyverse)
library(lubridate)
library(gganimate)
library(gridExtra)
library(kableExtra)
library(ggplot2)
library(basemaps)
library(ggmap)
library(viridis)

# R options setup
options(scipen = 999)
options(tigris_class = "sf")

# additional functions from PPA book
root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")


# function shortcuts
g <- glimpse
m <- mapview
len <- length
st_c <- st_coordinates

# Gillian's working directory
setwd("C:/Users/m1861/Desktop/CPLN790_MUSAPracticum/MUSA801_PLA")

# color scheme
# https://coolors.co/b98b73-cb997e-ddbea9-ffe8d6-d4c7b0-b7b7a4-a5a58d-6b705c-3f4238 
gillianpick <- c("#3f4238", "#b98b73", "#f6bd60", "#ff758f", "#2a9d8f")
#               dark green, dark brown, highlight yellow, highlight pink, highlight blue
```

# functions
```{r}
# ggplot map theme for us to build on
mapTheme_ggplot <- function() {
  theme(
    rect = element_rect(fill = "transparent") # this set the background transparent
    )
}
mapGuide_ggplot <- function() {
  guides(
    colour = guide_legend(override.aes = list(size=5)) # this set the size for the point on legend
    ) 
}

chartTheme_ggplot <- function() {
  theme(
    rect = element_rect(fill = "transparent"), # this set the background transparent
    axis.text = element_text(size=12),
    axis.title.x = element_text(size=12),
    axis.title.y = element_text(size=12),
  )
}


# save ggplot map configurations
mapSave_ggplot <- function(fileName) {
  ggsave(paste("visualizations/1st_presentation/", fileName, ".png", sep=""), #Gillian's path
         plot = last_plot(), dpi = 300, 
         width = 8, height = 5, units = "in", bg = "transparent")
}

chartSave_ggplot <- function(fileName) {
  ggsave(paste("visualizations/1st_presentation/", fileName, ".png", sep=""), #Gillian's path
         plot = last_plot(), dpi = 300, 
         width = 8, height = 5, units = "in", bg = "transparent")
}


```


# Read data that Adrian prepared
```{r}
# joined data
vacantLandProps <- readRDS("C:/Users/m1861/Desktop/CPLN790_MUSAPracticum/Data_Box/local/vacantLandProps.rds")
parcelsProps <- readRDS("C:/Users/m1861/Desktop/CPLN790_MUSAPracticum/Data_Box/local/parcelProps.rds")
permitsProps <- readRDS("C:/Users/m1861/Desktop/CPLN790_MUSAPracticum/Data_Box/local/permitsProps.rds")
transfersProps <- readRDS("C:/Users/m1861/Desktop/CPLN790_MUSAPracticum/Data_Box/local/transfersProps.rds")
delinquenciesProps <- readRDS("C:/Users/m1861/Desktop/CPLN790_MUSAPracticum/Data_Box/local/delinquenciesProps.rds")

# joined data created by Gillian
delinquenciesProps_allYrs <- readRDS("C:/Users/m1861/Desktop/CPLN790_MUSAPracticum/Data_Box/local/delinquenciesProps_allYrs.rds")
transfersProps_allYrs <- readRDS("C:/Users/m1861/Desktop/CPLN790_MUSAPracticum/Data_Box/local/transfersProps_allYrs.rds")
zoningPermitsProps_allYrs <- readRDS("C:/Users/m1861/Desktop/CPLN790_MUSAPracticum/Data_Box/local/zoningPermitsProps_allYrs.rds")


phlcrs <- 'EPSG:32129' #'EPSG:3364' #'EPSG:4269'
# get geometry for the county of Philadelphia
phlcounty <- tigris::counties(state = 42) %>%
  filter(GEOID == '42101') %>%
  dplyr::select(GEOID, geometry) %>%
  st_transform(st_crs(phlcrs))
```

# fishnet
```{r}
fishnet <- phlcounty %>%
  st_make_grid(.,
               cellsize = 250, 
               square = TRUE) %>%
  .[phlcounty] %>%                     # clip to Philadelphia County boundary
  st_sf() %>%
  mutate(uniqueID = rownames(.))
```


# map of vacant properties
```{r}
# base_map <- get_stamenmap(c(left = -75.34937, bottom = 39.84524, right = -74.92109, top = 40.17457),
#                            maptype = "terrain-background") # square
base_map <- get_stamenmap(c(left = -75.54937, bottom = 39.84524, right = -74.82109, top = 40.17457),
                           maptype = "terrain-background") # rectangle (wider)

ggmap(base_map) +
  geom_sf(data=phlcounty, inherit.aes = FALSE) + 
  geom_sf(data=vacantLandProps, color=gillianpick[2], size=0.01,
           inherit.aes = FALSE) +
  geom_sf(data=phlcounty, color=gillianpick[1], fill=NA, size=2, inherit.aes = FALSE) + 
  coord_sf(crs = st_crs(4326)) +
  mapTheme_ggplot()
  
#mapSave_ggplot("vacantProperties")
```

# tax delinquent vacant properties
```{r}
# map vacant properties (points)
delinquentVacantProps <- left_join(vacantLandProps, 
                                   delinquenciesProps_allYrs %>%
                                     st_drop_geometry(.) %>%
                                     mutate(delinquentStatus = 1), 
                                   by="parcel_number") %>%
  mutate(delinquentStatus = ifelse(is.na(delinquentStatus)==F, 1, 0)) %>%
  mutate(delinquentType = ifelse(liens_sold_1990s==TRUE, 2, delinquentStatus), 
         # delinquent type: 0 not delinquent, 1 delinquent, 2 us bank
         delinquentType = replace_na(delinquentType, 0))
# how many vacant delinquent?
num_delinquentVacant = sum(delinquentVacantProps$delinquentStatus, na.rm = T)
share_delinquentVacant = num_delinquentVacant/length(unique(vacantLandProps$parcel_number))

ggmap(base_map) +
  geom_sf(data=phlcounty, inherit.aes = FALSE) + 
  geom_sf(data=delinquentVacantProps, 
          aes(color=factor(delinquentStatus)), 
          size = 0.01, inherit.aes = FALSE) +
  geom_sf(data=phlcounty, color=gillianpick[1], fill=NA, size=2, inherit.aes = FALSE) + 
  coord_sf(crs = st_crs(4326)) +
  scale_color_manual("delinquent", values= c(gillianpick[2], gillianpick[3]), labels= c("no", "yes")) +
  mapGuide_ggplot() +
  mapTheme_ggplot()
#mapSave_ggplot("delinquentVacantProperties")


# map vacant properties (fishnet)
delinquentVacantNet <- delinquentVacantProps %>%
  mutate(vacant = 1) %>%
  select(delinquentStatus, vacant) %>%
  aggregate(fishnet, sum) %>% 
  mutate(countDelinquent = replace_na(delinquentStatus, 0),
         vacant = replace_na(vacant, 0)) %>%
  select(-delinquentStatus) %>%
  mutate(uniqueID = rownames(.),) %>%
  mutate(cvID = sample(round(nrow(fishnet)/24), size=nrow(fishnet), replace=T))

ggmap(base_map) +
  geom_sf(data=phlcounty, inherit.aes = FALSE) + 
  geom_sf(data=subset(delinquentVacantNet, vacant>0), aes(fill=countDelinquent), color=NA, inherit.aes = FALSE) +
  geom_sf(data=phlcounty, color=gillianpick[1], fill=NA, size=2, inherit.aes = FALSE) + 
  scale_fill_viridis(name="delinquencies") +
  coord_sf(crs = st_crs(4326)) 

#mapSave_ggplot("delinquentVacantProperties_fishnet")

# trend of delinquencies # whether it is vacant or not, doesn't matter
tab_delinquenciesProps_byYr <- delinquenciesProps %>%
  group_by(oldest_year_owed) %>%
  summarise(countProp = n()) %>%
  st_drop_geometry()

ggplot(tab_delinquenciesProps_byYr, aes(x=oldest_year_owed, y=countProp)) + 
  geom_line(color=gillianpick[2], size=1.5) + 
  geom_point(color=gillianpick[3], size=2.5) +
  xlab("year") +
  ylab("tax delinquent properties") +
  chartTheme_ggplot()

#chartSave_ggplot("delinquentTrend")

# trend of delinquencies of vacant properties
tab_delinquenciesProps_byYr <- delinquentVacantProps %>%
  group_by(oldest_year_owed) %>%
  summarise(countProp = n()) %>%
  st_drop_geometry()

ggplot(tab_delinquenciesProps_byYr, aes(x=oldest_year_owed, y=countProp)) + 
  geom_line(color=gillianpick[2], size=1.5) + 
  geom_point(color=gillianpick[3], size=2.5) +
  xlab("year") +
  ylab("tax delinquent vacant properties") +
  ylim(c(0, 1600)) +
  chartTheme_ggplot()

#chartSave_ggplot("delinquentVacantTrend")
```

# US bank liens
```{r}
tab_usbanklienProps <- delinquentVacantProps %>%
  filter(delinquentStatus==1) %>%
  group_by(liens_sold_1990s) %>%
  summarise(countUSBANK = n()) %>%
  st_drop_geometry()

ggplot(tab_usbanklienProps, aes(liens_sold_1990s, countUSBANK, fill=factor(liens_sold_1990s))) + 
  geom_bar(position = "dodge", stat = "summary", fun = "mean") +
  scale_fill_manual(values = c(gillianpick[3], gillianpick[4]),
                    name="") +
  scale_x_discrete(name ="US bank lien", 
                    labels=c("no", "yes")) +
  ylab("amount") +
  theme(legend.position="none") +
  chartTheme_ggplot()

#chartSave_ggplot("usbankBar")

ggmap(base_map) +
  geom_sf(data=phlcounty, inherit.aes = FALSE) + 
  geom_sf(data=delinquentVacantProps, 
          aes(color=factor(delinquentType)), 
          size = 0.01, inherit.aes = FALSE) +
  geom_sf(data=phlcounty, color=gillianpick[1], fill=NA, size=2, inherit.aes = FALSE) + 
  coord_sf(crs = st_crs(4326)) +
  scale_color_manual("category", values= c(gillianpick[2], gillianpick[3], gillianpick[4]), labels= c("vacant", "vacant and delinquent", "vacant, delinquent, us bank lien")) +
  mapGuide_ggplot() +
  mapTheme_ggplot()
#mapSave_ggplot("usbankVacantProperties")

usbankVacantNet <- delinquentVacantProps %>%
  mutate(vacant = 1,
         countUSbank = ifelse(liens_sold_1990s==TRUE, 1, 0)) %>%
  select(countUSbank, vacant) %>%
  aggregate(fishnet, sum) %>%
  mutate(uniqueID = rownames(.),
         countUSbank = replace_na(countUSbank, 0),
         vacant = replace_na(vacant, 0)) %>%
  mutate(cvID = sample(round(nrow(fishnet)/24), size=nrow(fishnet), replace=T))

ggmap(base_map) +
  geom_sf(data=phlcounty, inherit.aes = FALSE) + 
  geom_sf(data=subset(usbankVacantNet, vacant>0), aes(fill=countUSbank), color=NA, inherit.aes = FALSE) +
  geom_sf(data=phlcounty, color=gillianpick[1], fill=NA, size=2, inherit.aes = FALSE) + 
  scale_fill_viridis(name="us bank liens") +
  coord_sf(crs = st_crs(4326)) 

#mapSave_ggplot("usBankVacantProperties_fishnet")
```

# sheriff's sale
```{r}
# if a parcel_number has multiple deed, I manipulated data to shift deed sheriff first
# so distinct() will grab deed sheriff and neglect others
transfersProps <- transfersProps_allYrs %>% 
    mutate(document_type=factor(document_type, labels(c("DEED SHERIFF"=1, "DEED"=2, "DEED MISCELLANEOUS"=3, "DEED OF CONDEMNATION"=4,"DEED LAND BANK"=5, "DEED MISCELLANEOUS TAXABLE"=6)))) %>%
  arrange(parcel_number, document_type) 
transfersProps <- transfersProps %>%
  distinct(parcel_number, .keep_all = TRUE)

sheriffSale <- transfersProps %>%
  filter(document_type=="DEED SHERIFF") 

# join all sheriff sales info we have together
## sheriff sales data from transfers
delinquentVacantTransferProps <- left_join(delinquentVacantProps, 
                                           transfersProps %>%
                                             st_drop_geometry(),
                                           by="parcel_number") %>%
  distinct(parcel_number, .keep_all = TRUE)

# sheriff's sales 2021-22 from client
sheriffSale2122 <- read_csv('C:/Users/m1861/Desktop/CPLN790_MUSAPracticum/Data_Box/local/sheriffSale2122.csv') 
sheriffSale2122 <- distinct(sheriffSale2122, OPA, .keep_all=TRUE) # remove duplicates
delinquentVacantTransferProps  <- merge(delinquentVacantTransferProps, sheriffSale2122, 
                                        by.x="parcel_number", by.y="OPA", all.x=TRUE, no.dups=TRUE) 

# create a new variable that record sheriff sales from all sources
delinquentVacantTransferProps <- delinquentVacantTransferProps %>%
  mutate(past_sheriff_sale = ifelse(document_type=="DEED SHERIFF", 1, 0),   #-> (only past records)
         past_sheriff_sale = replace_na(past_sheriff_sale, 0),
         scheduled_sheriff_sale = ifelse(document_type=="DEED SHERIFF"|is.na(Status)==F|sheriff_sale=="Y", 1, 0),   #-> (only future records)
         scheduled_sheriff_sale = replace_na(scheduled_sheriff_sale, 0),
         all_sheriff_sale = ifelse(past_sheriff_sale==1 | scheduled_sheriff_sale==1, 1, 0),
         sheriff_sale_year = year(as.Date(display_date)), # transfer data
         # sheriff_sale_year = ifelse(sheriff_sale=="Y", year(as.Date(sale_date.x)), NA_character_), # delinquency data
         # sheriff_sale_year = ifelse(is.na(sheriff_sale_year)==T, year(strptime(`Bidding Open Date/Time`, format='%m/%j/%Y %I:%M %p')), sheriff_sale_year) # 2122 data
        ) 


# look at what's it like with all information combined
check_sheriff <- delinquentVacantTransferProps %>%
  #filter(document_type=="DEED SHERIFF") %>%
  select(parcel_number, past_sheriff_sale, sheriff_sale_year, document_type, sheriff_sale, Status, delinquentType, `Bidding Open Date/Time`, sheriff_sale_year, sale_date.x) %>%
  st_drop_geometry() 
                                  
check_sheriff_sale_and_usbank <- delinquentVacantTransferProps %>% # for past and scheduled sales
  filter(sheriff_sale=="Y"|past_sheriff_sale==1|is.na(Status)==F, liens_sold_1990s==TRUE)
# 189 for 2017 and onwards, 213 for all years when included sheriff sale from delinquency data. 
# 115 when excluded sheriff sale from delinquency data

check_sheriff_sale_and_usbank <- delinquentVacantTransferProps %>% # for past sales
  filter(past_sheriff_sale==1, liens_sold_1990s==TRUE)
# 98 for all years

ggmap(base_map) +
  geom_sf(data=phlcounty, inherit.aes = FALSE) + 
  geom_sf(data=subset(delinquentVacantTransferProps, delinquentStatus==1), 
          aes(color=factor(all_sheriff_sale)), 
          size = 0.01, inherit.aes = FALSE) +
  geom_sf(data=phlcounty, color=gillianpick[1], fill=NA, size=2, inherit.aes = FALSE) + 
  coord_sf(crs = st_crs(4326)) +
  scale_color_manual("category", values= c(gillianpick[3], gillianpick[5]), labels= c("vacant and delinquent", "vacant, delinquent, \nsheriff's sale")) +
  mapGuide_ggplot() +
  mapTheme_ggplot()
#mapSave_ggplot("sheriffSaleProperties_allYrs")

# trend of sheriff's sale 
# calculate how many sheriff sale for delinquent vacant properties 
tab_sheriffSaleProps <- delinquentVacantTransferProps %>%
  #filter(delinquentStatus==1) %>%
  #mutate(sheriff_sale = ifelse(document_type=="DEED SHERIFF", 1, sheriff_sale),
         # sheriff_sale = ifelse(sheriff_sale=="Y", 1, sheriff_sale),
         # sheriff_sale = ifelse(sheriff_sale=="N", 0, sheriff_sale),
         # sheriff_sale = replace_na(sheriff_sale, 0)) %>%
  group_by(all_sheriff_sale) %>%
  summarise(countSheriffSale = n()) %>%
  st_drop_geometry()

tab_sheriffSaleProps_byYr <- delinquentVacantTransferProps %>%
  filter(delinquentStatus==1) %>%
  # mutate(sheriff_sale = ifelse(document_type=="DEED SHERIFF", 1, sheriff_sale),
  #        sheriff_sale = ifelse(sheriff_sale=="Y", 1, sheriff_sale),
  #        sheriff_sale = ifelse(sheriff_sale=="N", 0, sheriff_sale),
  #        sheriff_sale = replace_na(sheriff_sale, 0)) %>%
  group_by(past_sheriff_sale, sheriff_sale_year) %>%
  summarise(countSheriffSale = n()) %>%
  st_drop_geometry() %>%
  filter(past_sheriff_sale==1)

# chart
ggplot(tab_sheriffSaleProps_byYr, aes(x=as.numeric(sheriff_sale_year), y=countSheriffSale)) + 
  geom_vline(xintercept = 2017, color = "#f9c74f", size=1) +
  geom_line(color=gillianpick[2], size=1.5) + 
  geom_point(color=gillianpick[5], size=2.5) +
  xlab("year") +
  scale_x_continuous(breaks=seq(from=1999,
                                to=2021,
                                by=2),
                     limits=c(1999, 2021)) +
  ylab("sheriff's sales") +
  geom_text(x = 2017, y=300, label="", angle = 0) +
  chartTheme_ggplot()

#chartSave_ggplot("sheriffSaleTrend")
```

# Construction permits
## basic map and time trend plot
```{r}
delinquentVacantTransferConstructionProps <- left_join(delinquentVacantTransferProps, 
                                           zoningPermitsProps_allYrs %>%
                                             st_drop_geometry(),
                                           by=c("parcel_number"="opa_account_num")) %>%
  distinct(parcel_number, .keep_all = TRUE)
  
# check_dupPermit <- delinquentVacantTransferConstructionProps %>%
#   filter(duplicated(parcel_number)) %>%
#   select(parcel_number, typeofwork, permitissuedate)

tab_permit_byYr <- delinquentVacantTransferConstructionProps %>%
  filter(is.na(permittype)==FALSE) %>%
  group_by(is.na(permittype), year(permitissuedate)) %>%
  summarise(countPermit = n()) %>%
  st_drop_geometry() 

tab_permitAll_byYr <- zoningPermitsProps_allYrs %>%
  group_by(is.na(permittype), year(permitissuedate)) %>%
  summarise(countPermit = n()) %>%
  st_drop_geometry() 

tab_permitBoth_byYr <- merge(tab_permit_byYr, tab_permitAll_byYr, by="year(permitissuedate)") %>%
  select(1,3,5) 
colnames(tab_permitBoth_byYr) <- c("year", "permitOnVacant", "permitPhilly")
tab_permitBoth_byYr <- tab_permitBoth_byYr %>%
  gather(key="variable", value="value", -year)

# map
ggmap(base_map) +
  geom_sf(data=phlcounty, inherit.aes = FALSE) + 
  geom_sf(data=delinquentVacantTransferConstructionProps, 
          aes(color=factor(is.na(permittype))), 
          size = 0.01, inherit.aes = FALSE) +
  geom_sf(data=phlcounty, color=gillianpick[1], fill=NA, size=2, inherit.aes = FALSE) + 
  coord_sf(crs = st_crs(4326)) +
  scale_color_manual("permits indicative of development", values= c(gillianpick[3], gillianpick[5]), labels= c("yes", "no")) +
  mapGuide_ggplot() +
  mapTheme_ggplot()
#mapSave_ggplot("permits_pts")

# chart
ggplot(data=tab_permitBoth_byYr, aes(x=year, y=value)) + 
  geom_line(aes(color=variable), size=1.5) + 
  geom_point(color=gillianpick[5], size=2.5) +
  # geom_line(data=tab_permit_byYr, aes(x=as.numeric(`year(permitissuedate)`), y=countPermit), color=gillianpick[2], size=1.5, linetype = variable) + 
  # geom_point(data=tab_permit_byYr, aes(x=as.numeric(`year(permitissuedate)`), y=countPermit), color=gillianpick[5], size=2.5) +
  xlab("year") +
  scale_x_continuous(breaks=seq(from=2005,
                                to=2025,
                                by=2)) +
  ylab("permits indicative of development") +
  scale_color_manual(values = c(gillianpick[2], gillianpick[3]),
                     labels = c("Vacant Sites", "Philadelphia"),
                     name="legend") +
  chartTheme_ggplot()

#chartSave_ggplot("permitsTrend")
```

## heat map
```{r}
# map vacant properties (fishnet)
zoningPermitsNet <-
  dplyr::select(zoningPermitsProps_allYrs) %>%
  st_set_crs(4319) %>%
  st_transform(., st_crs(phlcrs)) %>%
  mutate(countPermits = 1) %>%
  aggregate(fishnet, sum) %>%                                                   # used as a spatial join that sums
  mutate(countPermits = replace_na(countPermits, 0)) %>%
  mutate(uniqueID = rownames(.)) %>%
  mutate(cvID = sample(round(nrow(fishnet)/24), size=nrow(fishnet), replace=T))

ggmap(base_map) +
  geom_sf(data=phlcounty, inherit.aes = FALSE) + 
  geom_sf(data=subset(zoningPermitsNet, countPermits>0), aes(fill=countPermits), color=NA, inherit.aes = FALSE) +
  geom_sf(data=phlcounty, color=gillianpick[1], fill=NA, size=2, inherit.aes = FALSE) + 
  geom_sf(data=vacantLandProps, color=gillianpick[2], size=0.01, alpha=0.1,
         inherit.aes = FALSE) +
  scale_fill_viridis(name="permits") +
  coord_sf(crs = st_crs(4326))

#mapSave_ggplot("permits_vacantProp_overlay")
```

